import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://youtubetranscript.com"),
  title: {
    default: "YouTube Transcript Generator - Free Tool | Extract Video Transcripts",
    template: "%s | YouTube Transcript Generator",
  },
  description: "Free online tool to generate transcripts from YouTube videos. Extract captions in JSON, text, SRT, VTT, HTML formats. No signup required. Download YouTube subtitles instantly.",
  keywords: [
    "youtube transcript",
    "youtube transcript generator",
    "youtube transcript downloader",
    "youtube to text converter",
    "extract youtube captions",
    "youtube subtitle extractor",
    "youtube subtitle download",
    "free youtube transcript",
    "youtube video transcript",
    "youtube caption generator",
    "youtube transcript api",
    "youtube transcript extractor",
    "youtube subtitles to text",
    "download youtube subtitles",
    "youtube transcript maker",
    "youtube video to text",
    "youtube captions downloader",
    "free youtube subtitle",
    "youtube transcript free",
    "youtube auto transcript",
    "youtube closed captions",
    "youtube transcript tool",
    "youtube video transcription",
    "youtube transcript creator",
    "youtube caption extractor",
    "youtube transcript english",
    "youtube transcript spanish",
    "youtube transcript french",
    "youtube transcript german",
    "youtube transcript italian",
    "youtube transcript portuguese",
    "youtube transcript japanese",
    "youtube transcript korean",
    "youtube transcript chinese",
    "youtube transcript russian",
    "youtube transcript arabic",
    "youtube transcript hindi",
    "youtube transcript vietnamese",
    "youtube transcript thai",
    "youtube transcript indonesian",
    "youtube transcript dutch",
    "youtube transcript polish",
    "youtube transcript turkish",
    "youtube transcript swedish",
    "youtube transcript danish",
    "youtube transcript norwegian",
    "youtube subtitle download json",
    "youtube subtitle download srt",
    "youtube subtitle download vtt",
    "youtube subtitle download text",
    "youtube subtitle download html",
    "youtube captions to json",
    "youtube captions to srt",
    "youtube captions to vtt",
    "youtube captions to text",
    "youtube captions to html",
    "youtube captions downloader free",
    "youtube captions downloader online",
    "youtube captions downloader no signup",
    "youtube video transcript download",
    "youtube video subtitle download",
    "youtube video captions download",
    "youtube video to text converter",
    "youtube video transcription free",
    "youtube video transcription online",
    "youtube video to subtitles",
    "youtube video subtitle maker",
    "youtube video caption generator",
    "youtube automatic captions download",
    "youtube auto generated captions",
    "youtube manual captions download",
    "youtube community captions download",
    "youtube transcript not available",
    "youtube transcript error fix",
    "youtube transcript generator python",
    "youtube transcript generator nodejs",
    "youtube transcript generator javascript",
    "youtube transcript generator api",
    "youtube downloader transcript",
    "youtube video downloader transcript",
    "youtube mp3 downloader transcript",
    "youtube mp4 downloader transcript",
    "youtube audio downloader transcript",
    "youtube subtitle downloader",
    "youtube caption downloader",
    "youtube transcript downloader",
    "youtube video converter transcript",
    "youtube to mp3 converter transcript",
    "youtube to mp4 converter transcript",
    "youtube to wav converter transcript",
    "youtube to text converter",
    "youtube to srt converter",
    "youtube to vtt converter",
    "youtube to json converter",
    "youtube to html converter",
    "youtube subtitle maker",
    "youtube caption maker",
    "youtube transcript maker",
    "youtube auto caption",
    "youtube automatic caption",
    "youtube manual caption",
    "youtube community caption",
    "youtube closed caption generator",
    "youtube open caption generator",
    "youtube subtitle editor",
    "youtube caption editor",
    "youtube transcript editor",
    "generate transcript from youtube",
    "generate captions from youtube",
    "generate subtitles from youtube",
    "extract transcript from youtube video",
    "extract captions from youtube video",
    "extract subtitles from youtube video",
    "download transcript from youtube",
    "download captions from youtube",
    "download subtitles from youtube",
    "get transcript from youtube video",
    "get captions from youtube video",
    "get subtitles from youtube video",
    "fetch transcript from youtube video",
    "fetch captions from youtube video",
    "fetch subtitles from youtube video",
    "youtube to text",
    "youtube to srt",
    "youtube to vtt",
    "youtube to json",
    "youtube to html",
    "free youtube transcript generator",
    "online youtube transcript generator",
    "download youtube transcript",
    "get youtube transcript",
    "fetch youtube transcript",
    "extract youtube transcript",
    "youtube video text extraction",
    "youtube caption extraction",
    "youtube subtitle extraction",
    "youtube transcript extraction tool",
    "youtube auto transcript generator",
    "youtube automatic transcript generator",
    "generate transcript from youtube video",
    "download transcript from youtube video",
    "get transcript from youtube video",
    "fetch transcript from youtube video",
    "extract transcript from youtube video",
    "grab transcript from youtube video",
    "rip transcript from youtube video",
    "copy transcript from youtube video",
    "save transcript from youtube video",
    "export transcript from youtube video",
    "convert transcript from youtube video",
    "best youtube transcript downloader",
    "top youtube transcript downloader",
    "free youtube transcript downloader",
    "online youtube transcript downloader",
    "youtube transcript downloader no ads",
    "youtube transcript downloader no signup",
    "youtube transcript downloader chrome",
    "youtube transcript downloader firefox",
    "youtube transcript downloader extension",
    "youtube transcript downloader app",
    "youtube transcript downloader software",
    "youtube transcript downloader windows",
    "youtube transcript downloader mac",
    "youtube transcript downloader linux",
    "youtube transcript downloader android",
    "youtube transcript downloader ios",
    "youtube subtitle to text",
    "youtube caption to text",
    "youtube transcript to text",
    "youtube subtitles to text",
    "youtube captions to text",
    "youtube transcripts to text",
    "youtube subtitle to srt",
    "youtube caption to srt",
    "youtube transcript to srt",
    "youtube subtitles to srt",
    "youtube captions to srt",
    "youtube transcripts to srt",
    "youtube subtitle to vtt",
    "youtube caption to vtt",
    "youtube transcript to vtt",
    "youtube subtitles to vtt",
    "youtube captions to vtt",
    "youtube transcripts to vtt",
    "youtube subtitle to json",
    "youtube caption to json",
    "youtube transcript to json",
    "youtube subtitles to json",
    "youtube captions to json",
    "youtube transcripts to json",
    "extract subtitles from youtube",
    "extract captions from youtube",
    "extract transcript from youtube",
    "download subtitles from youtube",
    "download captions from youtube",
    "download transcript from youtube",
    "get subtitles from youtube",
    "get captions from youtube",
    "get transcript from youtube",
    "fetch subtitles from youtube",
    "fetch captions from youtube",
    "fetch transcript from youtube",
    "grab subtitles from youtube",
    "grab captions from youtube",
    "grab transcript from youtube",
    "rip subtitles from youtube",
    "rip captions from youtube",
    "rip transcript from youtube",
    "copy subtitles from youtube",
    "copy captions from youtube",
    "copy transcript from youtube",
    "save subtitles from youtube",
    "save captions from youtube",
    "save transcript from youtube",
    "export subtitles from youtube",
    "export captions from youtube",
    "export transcript from youtube",
    "convert subtitles from youtube",
    "convert captions from youtube",
    "convert transcript from youtube",
    "free youtube transcript tool",
    "free youtube subtitle tool",
    "free youtube caption tool",
    "free youtube transcript app",
    "free youtube subtitle app",
    "free youtube caption app",
    "free youtube transcript software",
    "free youtube subtitle software",
    "free youtube caption software",
    "free youtube transcript online",
    "free youtube subtitle online",
    "free youtube caption online",
    "free youtube transcript website",
    "free youtube subtitle website",
    "free youtube caption website",
    "free youtube transcript service",
    "free youtube subtitle service",
    "free youtube caption service",
    "best youtube transcript generator",
    "best youtube subtitle generator",
    "best youtube caption generator",
    "best free youtube transcript generator",
    "best free youtube subtitle generator",
    "best free youtube caption generator",
    "top youtube transcript generator",
    "top youtube subtitle generator",
    "top youtube caption generator",
    "youtube transcript generator tool",
    "youtube subtitle generator tool",
    "youtube caption generator tool",
    "youtube transcript generator app",
    "youtube subtitle generator app",
    "youtube caption generator app",
    "youtube transcript generator software",
    "youtube subtitle generator software",
    "youtube caption generator software",
    "youtube transcript generator online",
    "youtube subtitle generator online",
    "youtube caption generator online",
    "youtube transcript generator website",
    "youtube subtitle generator website",
    "youtube caption generator website",
    "youtube transcript generator download",
    "youtube subtitle generator download",
    "youtube caption generator download",
    "youtube transcript generator windows",
    "youtube subtitle generator windows",
    "youtube caption generator windows",
    "youtube transcript generator mac",
    "youtube subtitle generator mac",
    "youtube caption generator mac",
    "youtube transcript generator linux",
    "youtube subtitle generator linux",
    "youtube caption generator linux",
    "youtube transcript generator android",
    "youtube subtitle generator android",
    "youtube caption generator android",
    "youtube transcript generator ios",
    "youtube subtitle generator ios",
    "youtube caption generator ios",
    "youtube transcript generator chrome",
    "youtube subtitle generator chrome",
    "youtube caption generator chrome",
    "youtube transcript generator firefox",
    "youtube subtitle generator firefox",
    "youtube caption generator firefox",
    "youtube transcript generator safari",
    "youtube subtitle generator safari",
    "youtube caption generator safari",
    "youtube transcript generator edge",
    "youtube subtitle generator edge",
    "youtube caption generator edge",
    "youtube video text extraction free",
    "youtube video text extraction online",
    "youtube video text extraction no signup",
    "youtube video text extraction no registration",
    "youtube video text extraction no login",
    "youtube video text extraction no account",
    "youtube video text extraction unlimited",
    "youtube video text extraction fast",
    "youtube video text extraction quick",
    "youtube video text extraction easy",
    "youtube video text extraction simple",
    "youtube video text extraction automatic",
    "youtube video text extraction instant",
    "youtube video text extraction secure",
    "youtube video text extraction private",
    "youtube video text extraction anonymous",
    "youtube video text extraction no ads",
    "youtube video text extraction no watermark",
    "youtube video text extraction high quality",
    "youtube video text extraction accurate",
    "youtube video text extraction precise",
    "youtube video text extraction reliable",
    "youtube video text extraction best",
    "youtube video text extraction top",
    "youtube video text extraction popular",
    "youtube video text extraction trending",
    "youtube video text extraction viral",
    "youtube video transcript extraction free",
    "youtube video transcript extraction online",
    "youtube video transcript extraction no signup",
    "youtube video transcript extraction no registration",
    "youtube video transcript extraction no login",
    "youtube video transcript extraction no account",
    "youtube video transcript extraction unlimited",
    "youtube video transcript extraction fast",
    "youtube video transcript extraction quick",
    "youtube video transcript extraction easy",
    "youtube video transcript extraction simple",
    "youtube video transcript extraction automatic",
    "youtube video transcript extraction instant",
    "youtube video transcript extraction secure",
    "youtube video transcript extraction private",
    "youtube video transcript extraction anonymous",
    "youtube video transcript extraction no ads",
    "youtube video transcript extraction no watermark",
    "youtube video transcript extraction high quality",
    "youtube video transcript extraction accurate",
    "youtube video transcript extraction precise",
    "youtube video transcript extraction reliable",
    "youtube video transcript extraction best",
    "youtube video transcript extraction top",
    "youtube video transcript extraction popular",
    "youtube subtitle extraction free",
    "youtube subtitle extraction online",
    "youtube subtitle extraction no signup",
    "youtube subtitle extraction no registration",
    "youtube subtitle extraction no login",
    "youtube subtitle extraction no account",
    "youtube subtitle extraction unlimited",
    "youtube subtitle extraction fast",
    "youtube subtitle extraction quick",
    "youtube subtitle extraction easy",
    "youtube subtitle extraction simple",
    "youtube subtitle extraction automatic",
    "youtube subtitle extraction instant",
    "youtube subtitle extraction secure",
    "youtube subtitle extraction private",
    "youtube subtitle extraction anonymous",
    "youtube subtitle extraction no ads",
    "youtube subtitle extraction no watermark",
    "youtube subtitle extraction high quality",
    "youtube subtitle extraction accurate",
    "youtube subtitle extraction precise",
    "youtube subtitle extraction reliable",
    "youtube subtitle extraction best",
    "youtube subtitle extraction top",
    "youtube subtitle extraction popular",
    "youtube subtitle extraction trending",
    "youtube caption extraction free",
    "youtube caption extraction online",
    "youtube caption extraction no signup",
    "youtube caption extraction no registration",
    "youtube caption extraction no login",
    "youtube caption extraction no account",
    "youtube caption extraction unlimited",
    "youtube caption extraction fast",
    "youtube caption extraction quick",
    "youtube caption extraction easy",
    "youtube caption extraction simple",
    "youtube caption extraction automatic",
    "youtube caption extraction instant",
    "youtube caption extraction secure",
    "youtube caption extraction private",
    "youtube caption extraction anonymous",
    "youtube caption extraction no ads",
    "youtube caption extraction no watermark",
    "youtube caption extraction high quality",
    "youtube caption extraction accurate",
    "youtube caption extraction precise",
    "youtube caption extraction reliable",
    "youtube caption extraction best",
    "youtube caption extraction top",
    "youtube caption extraction popular",
    "youtube caption extraction trending",
    "youtube subtitle maker free",
    "youtube caption maker free",
    "youtube transcript maker free",
    "youtube subtitle maker online",
    "youtube caption maker online",
    "youtube transcript maker online",
    "youtube subtitle maker download",
    "youtube caption maker download",
    "youtube transcript maker download",
    "youtube subtitle maker software",
    "youtube caption maker software",
    "youtube transcript maker software",
    "youtube subtitle maker app",
    "youtube caption maker app",
    "youtube transcript maker app",
    "youtube subtitle maker tool",
    "youtube caption maker tool",
    "youtube transcript maker tool",
    "youtube subtitle maker website",
    "youtube caption maker website",
    "youtube transcript maker website",
    "youtube subtitle maker service",
    "youtube caption maker service",
    "youtube transcript maker service",
    "youtube subtitle maker api",
    "youtube caption maker api",
    "youtube transcript maker api",
    "youtube subtitle maker python",
    "youtube caption maker python",
    "youtube transcript maker python",
    "youtube subtitle maker javascript",
    "youtube caption maker javascript",
    "youtube transcript maker javascript",
    "youtube subtitle maker nodejs",
    "youtube caption maker nodejs",
    "youtube transcript maker nodejs",
    "youtube subtitle maker react",
    "youtube caption maker react",
    "youtube transcript maker react",
    "youtube subtitle maker vue",
    "youtube caption maker vue",
    "youtube transcript maker vue",
    "youtube subtitle maker angular",
    "youtube caption maker angular",
    "youtube transcript maker angular",
    "youtube subtitle maker svelte",
    "youtube caption maker svelte",
    "youtube transcript maker svelte",
    "youtube subtitle maker nextjs",
    "youtube caption maker nextjs",
    "youtube transcript maker nextjs",
    "youtube subtitle generator free tool",
    "youtube caption generator free tool",
    "youtube transcript generator free tool",
    "youtube subtitle generator free software",
    "youtube caption generator free software",
    "youtube transcript generator free software",
    "youtube subtitle generator free app",
    "youtube caption generator free app",
    "youtube transcript generator free app",
    "youtube subtitle generator free online",
    "youtube caption generator free online",
    "youtube transcript generator free online",
    "youtube subtitle generator no signup",
    "youtube caption generator no signup",
    "youtube transcript generator no signup",
    "youtube subtitle generator no registration",
    "youtube caption generator no registration",
    "youtube transcript generator no registration",
    "youtube subtitle generator no login",
    "youtube caption generator no login",
    "youtube transcript generator no login",
    "youtube subtitle generator no account",
    "youtube caption generator no account",
    "youtube transcript generator no account",
    "youtube subtitle generator unlimited",
    "youtube caption generator unlimited",
    "youtube transcript generator unlimited",
    "youtube subtitle generator fast",
    "youtube caption generator fast",
    "youtube transcript generator fast",
    "youtube subtitle generator quick",
    "youtube caption generator quick",
    "youtube transcript generator quick",
    "youtube subtitle generator easy",
    "youtube caption generator easy",
    "youtube transcript generator easy",
    "youtube subtitle generator simple",
    "youtube caption generator simple",
    "youtube transcript generator simple",
    "youtube subtitle generator automatic",
    "youtube caption generator automatic",
    "youtube transcript generator automatic",
    "youtube subtitle generator instant",
    "youtube caption generator instant",
    "youtube transcript generator instant",
    "youtube subtitle generator secure",
    "youtube caption generator secure",
    "youtube transcript generator secure",
    "youtube subtitle generator private",
    "youtube caption generator private",
    "youtube transcript generator private",
    "youtube subtitle generator anonymous",
    "youtube caption generator anonymous",
    "youtube transcript generator anonymous",
    "youtube subtitle generator no ads",
    "youtube caption generator no ads",
    "youtube transcript generator no ads",
    "youtube subtitle generator no watermark",
    "youtube caption generator no watermark",
    "youtube transcript generator no watermark",
    "youtube subtitle generator high quality",
    "youtube caption generator high quality",
    "youtube transcript generator high quality",
    "youtube subtitle generator accurate",
    "youtube caption generator accurate",
    "youtube transcript generator accurate",
    "youtube subtitle generator precise",
    "youtube caption generator precise",
    "youtube transcript generator precise",
    "youtube subtitle generator reliable",
    "youtube caption generator reliable",
    "youtube transcript generator reliable",
    "youtube subtitle generator best",
    "youtube caption generator best",
    "youtube transcript generator best",
    "youtube subtitle generator top",
    "youtube caption generator top",
    "youtube transcript generator top",
    "youtube subtitle generator popular",
    "youtube caption generator popular",
    "youtube transcript generator popular",
    "youtube subtitle generator trending",
    "youtube caption generator trending",
    "youtube transcript generator trending",
    "youtube subtitle generator viral",
    "youtube caption generator viral",
    "youtube transcript generator viral",
    "youtube subtitle generator hot",
    "youtube caption generator hot",
    "youtube transcript generator hot",
    "youtube subtitle generator new",
    "youtube caption generator new",
    "youtube transcript generator new",
    "youtube subtitle generator latest",
    "youtube caption generator latest",
    "youtube transcript generator latest",
    "youtube subtitle generator review",
    "youtube caption generator review",
    "youtube transcript generator review",
    "youtube subtitle generator reviews",
    "youtube caption generator reviews",
    "youtube transcript generator reviews",
    "youtube subtitle generator rating",
    "youtube caption generator rating",
    "youtube transcript generator rating",
    "youtube subtitle generator ratings",
    "youtube caption generator ratings",
    "youtube transcript generator ratings",
    "youtube subtitle generator comparison",
    "youtube caption generator comparison",
    "youtube transcript generator comparison",
    "youtube subtitle generator vs",
    "youtube caption generator vs",
    "youtube transcript generator vs",
    "youtube subtitle generator alternative",
    "youtube caption generator alternative",
    "youtube transcript generator alternative",
    "youtube subtitle generator alternatives",
    "youtube caption generator alternatives",
    "youtube transcript generator alternatives",
    "youtube subtitle generator similar",
    "youtube caption generator similar",
    "youtube transcript generator similar",
    "youtube subtitle generator like",
    "youtube caption generator like",
    "youtube transcript generator like",
    "youtube subtitle generator similar to",
    "youtube caption generator similar to",
    "youtube transcript generator similar to",
    "youtube subtitle generator competitors",
    "youtube caption generator competitors",
    "youtube transcript generator competitors",
    "youtube subtitle generator replacement",
    "youtube caption generator replacement",
    "youtube transcript generator replacement",
    "youtube subtitle generator substitute",
    "youtube caption generator substitute",
    "youtube transcript generator substitute",
    "youtube subtitle generator instead of",
    "youtube caption generator instead of",
    "youtube transcript generator instead of",
    "youtube subtitle generator better than",
    "youtube caption generator better than",
    "youtube transcript generator better than",
    "youtube subtitle generator free alternative",
    "youtube caption generator free alternative",
    "youtube transcript generator free alternative",
    "youtube subtitle generator premium",
    "youtube caption generator premium",
    "youtube transcript generator premium",
    "youtube subtitle generator pro",
    "youtube caption generator pro",
    "youtube transcript generator pro",
    "youtube subtitle generator paid",
    "youtube caption generator paid",
    "youtube transcript generator paid",
    "youtube subtitle generator subscription",
    "youtube caption generator subscription",
    "youtube transcript generator subscription",
    "youtube subtitle generator pricing",
    "youtube caption generator pricing",
    "youtube transcript generator pricing",
    "youtube subtitle generator price",
    "youtube caption generator price",
    "youtube transcript generator price",
    "youtube subtitle generator cost",
    "youtube caption generator cost",
    "youtube transcript generator cost",
    "youtube subtitle generator fee",
    "youtube caption generator fee",
    "youtube transcript generator fee",
    "youtube subtitle generator discount",
    "youtube caption generator discount",
    "youtube transcript generator discount",
    "youtube subtitle generator coupon",
    "youtube caption generator coupon",
    "youtube transcript generator coupon",
    "youtube subtitle generator promo code",
    "youtube caption generator promo code",
    "youtube transcript generator promo code",
    "youtube subtitle generator deal",
    "youtube caption generator deal",
    "youtube transcript generator deal",
    "youtube subtitle generator offer",
    "youtube caption generator offer",
    "youtube transcript generator offer",
    "youtube subtitle generator sale",
    "youtube caption generator sale",
    "youtube transcript generator sale",
    "youtube subtitle generator ai powered",
    "youtube caption generator ai powered",
    "youtube transcript generator ai powered",
    "youtube subtitle generator artificial intelligence",
    "youtube caption generator artificial intelligence",
    "youtube transcript generator artificial intelligence",
    "youtube subtitle generator machine learning",
    "youtube caption generator machine learning",
    "youtube transcript generator machine learning",
    "youtube subtitle generator deep learning",
    "youtube caption generator deep learning",
    "youtube transcript generator deep learning",
    "youtube subtitle generator neural network",
    "youtube caption generator neural network",
    "youtube transcript generator neural network",
    "youtube subtitle generator natural language processing",
    "youtube caption generator natural language processing",
    "youtube transcript generator natural language processing",
    "youtube subtitle generator nlp",
    "youtube caption generator nlp",
    "youtube transcript generator nlp",
    "youtube subtitle generator speech to text",
    "youtube caption generator speech to text",
    "youtube transcript generator speech to text",
    "youtube subtitle generator stt",
    "youtube caption generator stt",
    "youtube transcript generator stt",
    "youtube subtitle generator voice recognition",
    "youtube caption generator voice recognition",
    "youtube transcript generator voice recognition",
    "youtube subtitle generator automatic speech recognition",
    "youtube caption generator automatic speech recognition",
    "youtube transcript generator automatic speech recognition",
    "youtube subtitle generator asr",
    "youtube caption generator asr",
    "youtube transcript generator asr",
    "youtube subtitle generator whisper",
    "youtube caption generator whisper",
    "youtube transcript generator whisper",
    "youtube subtitle generator openai whisper",
    "youtube caption generator openai whisper",
    "youtube transcript generator openai whisper",
    "subtitle generator",
    "caption generator",
    "transcript generator",
    "video subtitle generator",
    "video caption generator",
    "video transcript generator",
    "youtube video subtitle",
    "youtube video caption",
    "youtube video transcript",
    "youtube video subtitles download",
    "youtube video captions download",
    "youtube video transcript download",
    "youtube video subtitles to text",
    "youtube video captions to text",
    "youtube video transcript to text",
    "youtube video subtitles to srt",
    "youtube video captions to srt",
    "youtube video transcript to srt",
    "youtube video subtitles to vtt",
    "youtube video captions to vtt",
    "youtube video transcript to vtt",
    "youtube video subtitles to json",
    "youtube video captions to json",
    "youtube video transcript to json",
    "youtube video subtitles to html",
    "youtube video captions to html",
    "youtube video transcript to html",
    "youtube audio transcript",
    "youtube audio subtitles",
    "youtube audio captions",
    "youtube audio transcript download",
    "youtube audio subtitles download",
    "youtube audio captions download",
    "youtube live transcript",
    "youtube live subtitles",
    "youtube live captions",
    "youtube live transcript download",
    "youtube live subtitles download",
    "youtube live captions download",
    "youtube stream transcript",
    "youtube stream subtitles",
    "youtube stream captions",
    "youtube premiere transcript",
    "youtube premiere subtitles",
    "youtube premiere captions",
    "youtube automatic captions",
    "youtube auto captions",
    "youtube community captions",
    "youtube manual captions",
    "youtube cc download",
    "youtube cc subtitles",
    "youtube closed captions download",
    "youtube closed captions subtitles",
    "youtube open captions",
    "download youtube subtitles",
    "download youtube captions",
    "download youtube transcript",
    "get youtube subtitles",
    "get youtube captions",
    "get youtube transcript",
    "fetch youtube subtitles",
    "fetch youtube captions",
    "fetch youtube transcript",
    "grab youtube subtitles",
    "grab youtube captions",
    "grab youtube transcript",
    "rip youtube subtitles",
    "rip youtube captions",
    "rip youtube transcript",
    "copy youtube subtitles",
    "copy youtube captions",
    "copy youtube transcript",
    "save youtube subtitles",
    "save youtube captions",
    "save youtube transcript",
    "export youtube subtitles",
    "export youtube captions",
    "export youtube transcript",
    "convert youtube subtitles",
    "convert youtube captions",
    "convert youtube transcript",
    "best youtube subtitle downloader",
    "best youtube caption downloader",
    "best youtube transcript downloader",
    "top youtube subtitle downloader",
    "top youtube caption downloader",
    "top youtube transcript downloader",
    "free youtube subtitle downloader",
    "free youtube caption downloader",
    "free youtube transcript downloader",
    "online youtube subtitle downloader",
    "online youtube caption downloader",
    "online youtube transcript downloader",
    "youtube subtitle downloader tool",
    "youtube caption downloader tool",
    "youtube transcript downloader tool",
    "youtube subtitle downloader app",
    "youtube caption downloader app",
    "youtube transcript downloader app",
    "youtube subtitle downloader software",
    "youtube caption downloader software",
    "youtube transcript downloader software",
    "youtube subtitle downloader website",
    "youtube caption downloader website",
    "youtube transcript downloader website",
    "youtube subtitle downloader service",
    "youtube caption downloader service",
    "youtube transcript downloader service",
    "youtube subtitle downloader api",
    "youtube caption downloader api",
    "youtube transcript downloader api",
    "youtube subtitle downloader python",
    "youtube caption downloader python",
    "youtube transcript downloader python",
    "youtube subtitle downloader javascript",
    "youtube caption downloader javascript",
    "youtube transcript downloader javascript",
    "youtube subtitle downloader nodejs",
    "youtube caption downloader nodejs",
    "youtube transcript downloader nodejs",
    "youtube subtitle downloader no ads",
    "youtube caption downloader no ads",
    "youtube transcript downloader no ads",
    "youtube subtitle downloader no signup",
    "youtube caption downloader no signup",
    "youtube transcript downloader no signup",
    "youtube subtitle downloader chrome extension",
    "youtube caption downloader chrome extension",
    "youtube transcript downloader chrome extension",
    "youtube subtitle downloader firefox extension",
    "youtube caption downloader firefox extension",
    "youtube transcript downloader firefox extension",
    "subtitle extractor",
    "caption extractor",
    "transcript extractor",
    "youtube subtitle extractor",
    "youtube caption extractor",
    "youtube transcript extractor",
    "extract subtitles",
    "extract captions",
    "extract transcript",
    "subtitle to text",
    "caption to text",
    "transcript to text",
    "subtitle to srt",
    "caption to srt",
    "transcript to srt",
    "subtitle to vtt",
    "caption to vtt",
    "transcript to vtt",
    "subtitle to json",
    "caption to json",
    "transcript to json",
    "subtitle to html",
    "caption to html",
    "transcript to html",
    "subtitle to xml",
    "caption to xml",
    "transcript to xml",
    "subtitle to ass",
    "caption to ass",
    "transcript to ass",
    "subtitle to ssa",
    "caption to ssa",
    "transcript to ssa",
    "subtitle to ttml",
    "caption to ttml",
    "transcript to ttml",
    "subtitle to sbv",
    "caption to sbv",
    "transcript to sbv",
    "subtitle to lrc",
    "caption to lrc",
    "transcript to lrc",
    "subtitle to txt",
    "caption to txt",
    "transcript to txt",
  ],
  authors: [{ name: "YouTube Transcript Generator" }],
  creator: "YouTube Transcript Generator",
  publisher: "YouTube Transcript Generator",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://youtubetranscript.com",
    siteName: "YouTube Transcript Generator",
    title: "YouTube Transcript Generator - Free Tool | Extract Video Transcripts",
    description: "Free online tool to generate transcripts from YouTube videos. Extract captions in JSON, text, SRT, VTT, HTML formats. No signup required. Download YouTube subtitles instantly.",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "YouTube Transcript Generator - Free Tool to Extract Video Transcripts",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "YouTube Transcript Generator - Free Tool | Extract Video Transcripts",
    description: "Free online tool to generate transcripts from YouTube videos. Extract captions in JSON, text, SRT, VTT, HTML formats.",
    images: ["/og-image.png"],
    creator: "@youtubetranscript",
    site: "@youtubetranscript",
  },
  alternates: {
    canonical: "https://youtubetranscript.com",
    languages: {
      en: "https://youtubetranscript.com",
    },
  },
  category: "technology",
  classification: "Free Tools, YouTube, Transcription, Video Processing",
  other: {
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "black-translucent",
    "apple-mobile-web-app-title": "YouTube Transcript",
    "application-name": "YouTube Transcript Generator",
    "msapplication-TileColor": "#000000",
    "msapplication-tap-highlight": "no",
    "theme-color": "#000000",
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      name: "YouTube Transcript Generator",
      url: "https://youtubetranscript.com",
      description: "Free online tool to generate transcripts from YouTube videos",
      publisher: {
        "@type": "Organization",
        name: "YouTube Transcript Generator",
      },
      potentialAction: {
        "@type": "SearchAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate: "https://youtubetranscript.com?videoUrl={search_term_string}",
        },
        "query-input": "required name=search_term_string",
      },
    },
    {
      "@type": "WebApplication",
      name: "YouTube Transcript Generator",
      url: "https://youtubetranscript.com",
      description: "Free tool to extract transcripts from YouTube videos in multiple formats",
      applicationCategory: "UtilitiesApplication",
      operatingSystem: "Web Browser",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
      },
      browserRequirements: "Requires JavaScript",
    },
    {
      "@type": "SoftwareApplication",
      name: "YouTube Transcript Generator",
      url: "https://youtubetranscript.com",
      description: "Free online tool to generate transcripts from YouTube videos. Extract captions in JSON, text, SRT, VTT, HTML formats.",
      applicationCategory: "UtilitiesApplication",
      operatingSystem: "Web Browser, Windows, Mac, Linux, Android, iOS",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
      },
      aggregateRating: {
        "@type": "AggregateRating",
        ratingValue: "4.8",
        reviewCount: "1000",
      },
    },
    {
      "@type": "FAQPage",
      mainEntity: [
        {
          "@type": "Question",
          name: "Is YouTube Transcript Generator free?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, YouTube Transcript Generator is completely free to use. No signup required.",
          },
        },
        {
          "@type": "Question",
          name: "What formats can I download transcripts in?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "You can download transcripts in JSON, plain text, SRT, VTT, and HTML formats.",
          },
        },
        {
          "@type": "Question",
          name: "Does this work with all YouTube videos?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "It works with most YouTube videos that have captions or subtitles available.",
          },
        },
        {
          "@type": "Question",
          name: "Can I get transcripts in different languages?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, you can select from multiple languages including English, Spanish, French, German, Italian, Portuguese, Japanese, Korean, Chinese, and more.",
          },
        },
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {children}
          <Toaster position="top-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
